### ISSUE TITLE
osbs uses system:anonymous no matter what username passed in

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/osbs-client#164]
I am attempting to pass an username to osbs but it appears to not be using it when calling to the OpenShift REST API. This is using a build off of latest git master as of this afternoon I made with `tito build --rpm --test --builder mock --arg mock=epel-7-x86_64`

```
# osbs --verbose --username system:builder get-user
2015-07-23 16:05:02,344 - osbs - DEBUG - Logging level set to debug
* About to connect() to localhost port 8443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=192.168.122.36
*       start date: Jul 14 21:08:46 2015 GMT
*       expire date: Jul 13 21:08:47 2016 GMT
*       common name: 192.168.122.36
*       issuer: CN=openshift-signer@1436908122
> GET /osapi/v1beta3/users/~/ HTTP/1.1
User-Agent: PycURL/7.29.0
Host: localhost:8443
Accept: */*

< HTTP/1.1 403 Forbidden
< Cache-Control: no-store
< Content-Type: application/json
< Date: Thu, 23 Jul 2015 21:05:02 GMT
< Content-Length: 227
< 
* Connection #0 to host localhost left intact
2015-07-23 16:05:02,573 - osbs.core - ERROR - [403] {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot get users at the cluster scope",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
Traceback (most recent call last):
  File "/usr/bin/osbs", line 9, in <module>
    load_entry_point('osbs==0.14', 'console_scripts', 'osbs')()
  File "/usr/lib/python2.7/site-packages/osbs/cli/main.py", line 353, in main
    args.func(args, osbs)
  File "/usr/lib/python2.7/site-packages/osbs/cli/main.py", line 197, in cmd_get_user
    user_json = osbs.get_user()
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 327, in get_user
    return self.os.get_user(username).json()
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 131, in get_user
    check_response(response)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 37, in check_response
    raise OsbsResponseException(message=response.content, status_code=response.status_code)
osbs.exceptions.OsbsResponseException: {
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot get users at the cluster scope",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

**Comment by maxamillion** [comment]
If I pass a `--username` and `--password` I get something different:

```
# osbs --verbose --username $USER --password $PASS build -g https://github.com/maxamillion/atomic-reactor-dockerfile-test.git -c test-image -u builder
2015-07-23 17:31:51,549 - osbs - DEBUG - Logging level set to debug
2015-07-23 17:31:51,549 - osbs.build.build_request - DEBUG - Instantiating: SimpleBuild((), {'build_json_store': '/usr/share/osbs/'})
2015-07-23 17:31:51,549 - osbs.build.build_request - DEBUG - setting params '{'component': 'test-image', 'git_uri': 'https://github.com/maxamillion/atomic-reactor-dockerfile-test.git', 'metadata_plugin_use_auth': None, 'yum_repourls': None, 'user': 'builder', 'openshift_uri': 'https://localhost:8443/', 'git_ref': u'master', 'registry_uri': 'http://localhost:5000/'}' for Spec({'required_params': [BuildParam(git_uri='None'), BuildParam(git_ref='master'), BuildParam(user='None'), BuildParam(component='None'), BuildParam(registry_uri='None'), BuildParam(openshift_uri='None')]})
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - git_uri = 'https://github.com/maxamillion/atomic-reactor-dockerfile-test.git'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - git_ref = 'master'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - user = 'builder'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - component = 'test-image'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - registry_uri = 'http://localhost:5000/'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - openshift_uri = 'https://localhost:8443/'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - yum_repourls = '[]'
2015-07-23 17:31:51,550 - osbs.build.spec - DEBUG - metadata_plugin_use_auth = 'None'
2015-07-23 17:31:51,551 - osbs.build.spec - DEBUG - name = 'test-image-20150723-173151'
2015-07-23 17:31:51,551 - osbs.build.spec - DEBUG - image_tag = 'builder/test-image:20150723173151'
2015-07-23 17:31:51,551 - osbs.build.spec - INFO - Validating params of SimpleSpec
2015-07-23 17:31:51,551 - osbs.build.build_request - DEBUG - loading template from path /usr/share/osbs/simple.json
2015-07-23 17:31:51,551 - osbs.build.build_request - DEBUG - loading inner template from path /usr/share/osbs/simple_inner.json
2015-07-23 17:31:51,551 - osbs.build.build_request - DEBUG - {u'kind': u'Build', u'spec': {u'source': {u'git': {u'ref': u'master', u'uri': 'https://github.com/maxamillion/atomic-reactor-dockerfile-test.git'}, u'type': u'Git'}, u'strategy': {u'customStrategy': {u'exposeDockerSocket': True, u'from': {u'kind': u'ImageStreamTag', u'name': u'buildroot:latest'}, u'env': [{u'name': u'DOCK_PLUGINS', u'value': '{"prebuild_plugins": [{"name": "change_from_in_dockerfile"}, {"name": "dockerfile_content"}, {"args": {"registry_uri": "http://localhost:5000/", "insecure_registry": true}, "name": "change_source_registry"}], "postbuild_plugins": [{"args": {"image_id": "BUILT_IMAGE_ID"}, "name": "all_rpm_packages"}, {"args": {"url": "https://localhost:8443/", "verify_ssl": false}, "name": "store_metadata_in_osv3"}, {"name": "remove_built_image"}]}'}]}, u'type': u'Custom'}, u'output': {u'to': {u'kind': u'DockerImage', u'name': u'http://localhost:5000//builder/test-image:20150723173151'}}}, u'apiVersion': u'v1beta3', u'metadata': {u'name': u'test-image-20150723-173151'}}
2015-07-23 17:31:51,551 - osbs.core - DEBUG - {"kind": "Build", "spec": {"source": {"git": {"ref": "master", "uri": "https://github.com/maxamillion/atomic-reactor-dockerfile-test.git"}, "type": "Git"}, "strategy": {"customStrategy": {"exposeDockerSocket": true, "from": {"kind": "ImageStreamTag", "name": "buildroot:latest"}, "env": [{"name": "DOCK_PLUGINS", "value": "{\"prebuild_plugins\": [{\"name\": \"change_from_in_dockerfile\"}, {\"name\": \"dockerfile_content\"}, {\"args\": {\"registry_uri\": \"http://localhost:5000/\", \"insecure_registry\": true}, \"name\": \"change_source_registry\"}], \"postbuild_plugins\": [{\"args\": {\"image_id\": \"BUILT_IMAGE_ID\"}, \"name\": \"all_rpm_packages\"}, {\"args\": {\"url\": \"https://localhost:8443/\", \"verify_ssl\": false}, \"name\": \"store_metadata_in_osv3\"}, {\"name\": \"remove_built_image\"}]}"}]}, "type": "Custom"}, "output": {"to": {"kind": "DockerImage", "name": "http://localhost:5000//builder/test-image:20150723173151"}}}, "apiVersion": "v1beta3", "metadata": {"name": "test-image-20150723-173151"}}
2015-07-23 17:31:51,551 - osbs.core - INFO - using basic authentication
* About to connect() to localhost port 8443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=192.168.122.36
*       start date: Jul 14 21:08:46 2015 GMT
*       expire date: Jul 13 21:08:47 2016 GMT
*       common name: 192.168.122.36
*       issuer: CN=openshift-signer@1436908122
* Server auth using Basic with user 'system'
> GET /oauth/authorize?response_type=token&client_id=openshift-challenging-client HTTP/1.1
Authorization: Basic c3lzdGVtOmJ1aWxkZXI6cGFzc3dvcmQ=
User-Agent: PycURL/7.29.0
Host: localhost:8443
Accept: */*

< HTTP/1.1 500 Internal Server Error
< Date: Thu, 23 Jul 2015 22:31:51 GMT
< Content-Length: 35
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
2015-07-23 17:31:51,781 - osbs.http - DEBUG - raw headers: u'HTTP/1.1 500 Internal Server Error\r\nDate: Thu, 23 Jul 2015 22:31:51 GMT\r\nContent-Length: 35\r\nContent-Type: text/plain; charset=utf-8'
2015-07-23 17:31:51,782 - osbs.core - ERROR - [500] 'Location' header is missing in response, cannot retrieve token
Traceback (most recent call last):
  File "/usr/bin/osbs", line 9, in <module>
    load_entry_point('osbs==0.14', 'console_scripts', 'osbs')()
  File "/usr/lib/python2.7/site-packages/osbs/cli/main.py", line 353, in main
    args.func(args, osbs)
  File "/usr/lib/python2.7/site-packages/osbs/cli/main.py", line 131, in cmd_build
    namespace=osbs.build_conf.get_namespace(),
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 247, in create_build
    return self.create_simple_build(namespace=namespace, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 39, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
osbs.exceptions.OsbsException: ValueError(u'Token was not retrieved successfully.',)

Original traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 229, in create_simple_build
    response = self.os.create_build(json.dumps(build_json), namespace=namespace)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 141, in create_build
    headers={"Content-Type": "application/json"})
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 82, in _post
    headers, kwargs = self._request_args(with_auth, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/core.py", line 78, in _request_args
    raise ValueError("Token was not retrieved successfully.")
ValueError(u'Token was not retrieved successfully.',)
```

And on the server this shows up in 'journalctl -f --full --unit openshift-master`
```
Jul 23 17:31:51 losbs openshift-master[29556]: E0723 17:31:51.780835   29556 empties.go:28] AuthenticationError: Invalid Authorization header
```

Running OpenShift version `openshift-master-1.0.0-0.git.4227.6ffebda.el7.centos.x86_64`

**Comment by twaugh** [comment]
The `username` and `password` configuration options are for dealing with OpenShift being behind an authentication proxy using Basic auth. (You can also hide it behind an authentication proxy that uses Kerberos: see `use_kerberos`.)

**Comment by maxamillion** [comment]
If I try without passing username/password it fails because of a `osbs.exceptions.OsbsNetworkException: (422)` which seems like a strange error since I can actually contact OpenShift over the network and since I'm contacting it on localhost. Did I just miss something in the configuration?

```
# osbs --verbose build -g https://github.com/maxamillion/atomic-reactor-dockerfile-test.git -c test-image
 -u builder
2015-07-24 08:18:47,936 - osbs - DEBUG - Logging level set to debug
2015-07-24 08:18:47,936 - osbs.build.build_request - DEBUG - Instantiating: SimpleBuild((), {'build_json_store': '/usr/share/osbs/'})
2015-07-24 08:18:47,937 - osbs.build.build_request - DEBUG - setting params '{'component': 'test-image', 'git_uri': 'https://github.com/maxamillion/atomic-reactor-dockerfile-test.git', 'metadata_plugin_use_auth': None, 'yum_repourls': None, 'user': 'builder', 'openshift_uri': 'https://localhost:8443/', 'git_ref': u'master', 'registry_uri': 'http://localhost:5000/'}' for Spec({'required_params': [BuildParam(git_uri='None'), BuildParam(git_ref='master'), BuildParam(user='None'), BuildParam(component='None'), BuildParam(registry_uri='None'), BuildParam(openshift_uri='None')]})
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - git_uri = 'https://github.com/maxamillion/atomic-reactor-dockerfile-test.git'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - git_ref = 'master'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - user = 'builder'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - component = 'test-image'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - registry_uri = 'http://localhost:5000/'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - openshift_uri = 'https://localhost:8443/'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - yum_repourls = '[]'
2015-07-24 08:18:47,937 - osbs.build.spec - DEBUG - metadata_plugin_use_auth = 'None'
2015-07-24 08:18:47,938 - osbs.build.spec - DEBUG - name = 'test-image-20150724-081847'
2015-07-24 08:18:47,938 - osbs.build.spec - DEBUG - image_tag = 'builder/test-image:20150724081847'
2015-07-24 08:18:47,938 - osbs.build.spec - INFO - Validating params of SimpleSpec
2015-07-24 08:18:47,938 - osbs.build.build_request - DEBUG - loading template from path /usr/share/osbs/simple.json
2015-07-24 08:18:47,938 - osbs.build.build_request - DEBUG - loading inner template from path /usr/share/osbs/simple_inner.json
2015-07-24 08:18:47,938 - osbs.build.build_request - DEBUG - {u'kind': u'Build', u'spec': {u'source': {u'git': {u'ref': u'master', u'uri': 'https://github.com/maxamillion/atomic-reactor-dockerfile-test.git'}, u'type': u'Git'}, u'strategy': {u'customStrategy': {u'exposeDockerSocket': True, u'from': {u'kind': u'ImageStreamTag', u'name': u'buildroot:latest'}, u'env': [{u'name': u'DOCK_PLUGINS', u'value': '{"prebuild_plugins": [{"name": "change_from_in_dockerfile"}, {"name": "dockerfile_content"}, {"args": {"registry_uri": "http://localhost:5000/", "insecure_registry": true}, "name": "change_source_registry"}], "postbuild_plugins": [{"args": {"image_id": "BUILT_IMAGE_ID"}, "name": "all_rpm_packages"}, {"args": {"url": "https://localhost:8443/", "verify_ssl": false}, "name": "store_metadata_in_osv3"}, {"name": "remove_built_image"}]}'}]}, u'type': u'Custom'}, u'output': {u'to': {u'kind': u'DockerImage', u'name': u'http://localhost:5000//builder/test-image:20150724081847'}}}, u'apiVersion': u'v1beta3', u'metadata': {u'name': u'test-image-20150724-081847'}}
2015-07-24 08:18:47,938 - osbs.core - DEBUG - {"kind": "Build", "spec": {"source": {"git": {"ref": "master", "uri": "https://github.com/maxamillion/atomic-reactor-dockerfile-test.git"}, "type": "Git"}, "strategy": {"customStrategy": {"exposeDockerSocket": true, "from": {"kind": "ImageStreamTag", "name": "buildroot:latest"}, "env": [{"name": "DOCK_PLUGINS", "value": "{\"prebuild_plugins\": [{\"name\": \"change_from_in_dockerfile\"}, {\"name\": \"dockerfile_content\"}, {\"args\": {\"registry_uri\": \"http://localhost:5000/\", \"insecure_registry\": true}, \"name\": \"change_source_registry\"}], \"postbuild_plugins\": [{\"args\": {\"image_id\": \"BUILT_IMAGE_ID\"}, \"name\": \"all_rpm_packages\"}, {\"args\": {\"url\": \"https://localhost:8443/\", \"verify_ssl\": false}, \"name\": \"store_metadata_in_osv3\"}, {\"name\": \"remove_built_image\"}]}"}]}, "type": "Custom"}, "output": {"to": {"kind": "DockerImage", "name": "http://localhost:5000//builder/test-image:20150724081847"}}}, "apiVersion": "v1beta3", "metadata": {"name": "test-image-20150724-081847"}}
* About to connect() to localhost port 8443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* SSL connection using TLS_RSA_WITH_AES_128_CBC_SHA
* Server certificate:
*       subject: CN=192.168.122.36
*       start date: Jul 14 21:08:46 2015 GMT
*       expire date: Jul 13 21:08:47 2016 GMT
*       common name: 192.168.122.36
*       issuer: CN=openshift-signer@1436908122
> POST /osapi/v1beta3/namespaces/default/builds/ HTTP/1.1
User-Agent: PycURL/7.29.0
Host: localhost:8443
Accept: */*
Content-Type: application/json
Content-Length: 1020

* upload completely sent off: 1020 out of 1020 bytes
< HTTP/1.1 422 status code 422
< Cache-Control: no-store
< Content-Type: application/json
< Date: Fri, 24 Jul 2015 13:18:48 GMT
< Content-Length: 925
<
* Connection #0 to host localhost left intact
Traceback (most recent call last):
  File "/usr/bin/osbs", line 9, in <module>
    load_entry_point('osbs==0.14', 'console_scripts', 'osbs')()
  File "/usr/lib/python2.7/site-packages/osbs/cli/main.py", line 353, in main
    args.func(args, osbs)
  File "/usr/lib/python2.7/site-packages/osbs/cli/main.py", line 131, in cmd_build
    namespace=osbs.build_conf.get_namespace(),
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 247, in create_build
    return self.create_simple_build(namespace=namespace, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 28, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/osbs/api.py", line 231, in create_simple_build
    logger.debug(build_response.json)
  File "/usr/lib/python2.7/site-packages/osbs/build/build_response.py", line 36, in json
    self._json = self.request.json()
  File "/usr/lib/python2.7/site-packages/osbs/http.py", line 158, in json
    self._check_status_code()
  File "/usr/lib/python2.7/site-packages/osbs/http.py", line 185, in _check_status_code
    raise OsbsNetworkException(url, message, self.status_code)
osbs.exceptions.OsbsNetworkException: (422)
```

**Comment by TomasTomecek** [comment]
@maxamillion is this still an issue?
