### ISSUE TITLE
Show a better error message for a missing Name label

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/osbs-client#413]
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/koji/daemon.py", line 1161, in runTask
      response = (handler.run(),)\n  File "/usr/lib/python2.6/site-packages/koji/tasks.py", line 158, in run
          return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
            File "/usr/lib/python2.6/site-packages/koji/util.py", line 154, in call_with_argcheck
                return func(*args, **kwargs)\n  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 373, in handler
                    **create_build_args\n  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 37, in catch_exceptions
                        return func(*args, **kwargs)\n  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 358, in create_build
                            return self.create_prod_build(**kwargs)\n  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 48, in catch_exceptions
                                raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
                                OsbsException: KeyError(u\'Name\',)
```

**Comment by vrutkovs** [comment]
Duplicate of #480

**Comment by twaugh** [comment]
Actually of #412.

**Comment by twaugh** [comment]
Hmm, actually this is different after all.
