### ISSUE TITLE
py3: logs are displayed in one line 

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/osbs-client#461]
```
$ head /usr/bin/osbs -n 
#!/bin/python3
$ osbs <..> build-logs <build-id>
2016-10-03 10:55:14,894 - osbs - DEBUG - Logging level set to debug
2016-10-03 10:55:14,895 - osbs.core - DEBUG - using kerberos authentication
/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
2016-10-03 10:55:16,413 - osbs.http - DEBUG - cleaning up
2016-10-03 10:55:16,413 - osbs.core - DEBUG - fragment is 'access_token=1Ps8ugUf9zSa4k6ezhZccjMRwRwyOdxnlKVpeQD6fLE&expires_in=86400&token_type=Bearer'
/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
2016-10-03 10:55:17,482 - osbs.http - DEBUG - cleaning up
/usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
2016-10-03 10:55:18,861 - osbs.http - DEBUG - cleaning up
b'2016-09-30 12:32:13,554 - atomic_reactor.inner - DEBUG - getting build json from input osv3\n2016-09-30 12:32:13,554 - atomic_reactor.plugin - DEBUG - loading plugins from dir \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins\'\n2016-09-30 12:32:13,554 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/__init__.py\'\n2016-09-30 12:32:13,554 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_delete_from_registry.py\'\n2016-09-30 12:32:13,555 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_koji_promote.py\'\n2016-09-30 12:32:14,570 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_remove_built_image.py\'\n2016-09-30 12:32:14,571 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_store_logs_to_file.py\'\n2016-09-30 12:32:14,578 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/exit_store_metadata_in_osv3.py\'\n2016-09-30 12:32:14,587 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/input_env.py\'\n2016-09-30 12:32:14,588 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/input_osv3.py\'\n2016-09-30 12:32:14,588 - atomic_reactor.plugin - DEBUG - load file \'/usr/lib/python2.7/site-packages/atomic_reactor/plugins/input_path.py\'\n
```

**Comment by vrutkovs** [comment]
Probably related: I get
```
2016-10-03 10:59:37,034 - osbs.http - DEBUG - cleaning up
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/osbs/api.py", line 36, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/osbs/api.py", line 485, in wait_for_build_to_get_scheduled
    response = self.os.wait_for_build_to_get_scheduled(build_id)
  File "/usr/lib/python3.5/site-packages/osbs/core.py", line 631, in wait_for_build_to_get_scheduled
    build_response = self.wait(build_id, BUILD_FINISHED_STATES + BUILD_RUNNING_STATES)
  File "/usr/lib/python3.5/site-packages/osbs/core.py", line 585, in wait
    for changetype, obj in self.watch_resource("builds", build_id):
  File "/usr/lib/python3.5/site-packages/osbs/core.py", line 560, in watch_resource
    j = json.loads(line)
  File "/usr/lib64/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/osbs", line 11, in <module>
    load_entry_point('osbs-client==0.31', 'console_scripts', 'osbs')()
  File "/usr/lib/python3.5/site-packages/osbs/cli/main.py", line 697, in main
    args.func(args, osbs)
  File "/usr/lib/python3.5/site-packages/osbs/cli/main.py", line 289, in cmd_build
    build = osbs.wait_for_build_to_get_scheduled(build_id)
  File "/usr/lib/python3.5/site-packages/osbs/api.py", line 47, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
osbs.exceptions.OsbsException: TypeError("the JSON object must be str, not 'bytes'",)
```
when a build is started

**Comment by twaugh** [comment]
Does this only happen with Python 3?

**Comment by vrutkovs** [comment]
Yes, works fine in py2

**Comment by lkolacek** [comment]
Same with me

**Comment by vrutkovs** [comment]
My fault - I had a version with PR #458 installed, this is the only version I can reproduce the issue.
