### ISSUE TITLE
Conflict error when instantiating BuildConfig

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#708]
This traceback was observed from osbs-client-0.44:
```
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/koji/daemon.py", line 1219, in runTask
    response = (handler.run(),)
  File "/usr/lib/python2.6/site-packages/koji/tasks.py", line 162, in run
    return koji.util.call_with_argcheck(self.handler, self.params, self.opts)
  File "/usr/lib/python2.6/site-packages/koji/util.py", line 208, in call_with_argcheck
    return func(*args, **kwargs)
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 822, in handler
    module=opts.get('module', None),
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 478, in runBuilds
    results = [self.createContainer(**kwargs)]
  File "/usr/lib/koji-builder-plugins/builder_containerbuild.py", line 537, in createContainer
    build_response = create_method(**orchestrator_create_build_args)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 51, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 762, in create_orchestrator_build
    return self._do_create_prod_build(**kwargs)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 619, in _do_create_prod_build
    response = self._create_build_config_and_build(build_request)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 448, in _create_build_config_and_build
    build = BuildResponse(response.json())
  File "/usr/lib/python2.6/site-packages/osbs/http.py", line 213, in json
    raise OsbsResponseException(text, self.status_code)
OsbsResponseException: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on buildconfigs \"[...]\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"[...]","kind":"buildconfigs"},"code":409}
```

The exception came up through here: https://github.com/projectatomic/osbs-client/blob/0.44/osbs/api.py#L448

This suggests the buildconfigs/.../instantiate API call (https://github.com/projectatomic/osbs-client/blob/0.44/osbs/core.py#L353) failed with a 409 Conflict error.

Perhaps we are missing a `@retry_on_conflict` decorator in that code path?

Seen in task #14571552.

**Comment by yahzaa** [comment]
I want to work on this.

**Comment by twaugh** [comment]
I don't think the cause for this is understood. I'm not clear about why the buildconfigs/.../instantiate call would fail with 409. The best guess I have is that the specified buildconfig doesn't exist, but I can't see how that would be the case.

**Comment by twaugh** [comment]
Closing, since we have not seen this recur and do not understand the cause without additional data.
