### ISSUE TITLE
Inform user when openshift object does not exist

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/osbs-client#83]
When master returns 404, we should not traceback in CLI; instead we should inform that provided resource is not available.

**Comment by mmilata** [comment]
We no longer traceback when in non-verbose mode:
```
% osbs -i test get-build asdf
2015-10-27 17:22:33,599 - osbs.core - INFO - using basic authentication
2015-10-27 17:22:34,350 - osbs.core - ERROR - [404] {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "build \"asdf\" not found",
  "reason": "NotFound",
  "details": {
    "name": "asdf",
    "kind": "build"
  },
  "code": 404
}
2015-10-27 17:22:34,350 - osbs - ERROR - Server returned error 404: build "asdf" not found

% osbs --verbose -i test get-build asdf
...
2015-10-27 17:21:16,150 - osbs.core - ERROR - [404] {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "build \"asdf\" not found",
  "reason": "NotFound",
  "details": {
    "name": "asdf",
    "kind": "build"
  },
  "code": 404
}
Traceback (most recent call last):
  File "/home/mmilata/.local/bin/osbs", line 9, in <module>
    load_entry_point('osbs==0.14', 'console_scripts', 'osbs')()
  File "/home/mmilata/work/osbs-client/osbs/cli/main.py", line 488, in main
    args.func(args, osbs)
  File "/home/mmilata/work/osbs-client/osbs/cli/main.py", line 79, in cmd_get_build
    build = osbs.get_build(args.BUILD_ID[0], namespace=args.namespace)
  File "/home/mmilata/work/osbs-client/osbs/api.py", line 33, in catch_exceptions
    return func(*args, **kwargs)
  File "/home/mmilata/work/osbs-client/osbs/api.py", line 98, in get_build
    response = self.os.get_build(build_id, namespace=namespace)
  File "/home/mmilata/work/osbs-client/osbs/core.py", line 341, in get_build
    check_response(response)
  File "/home/mmilata/work/osbs-client/osbs/core.py", line 47, in check_response
    raise OsbsResponseException(message=content, status_code=response.status_code)
osbs.exceptions.OsbsResponseException: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "build \"asdf\" not found",
  "reason": "NotFound",
  "details": {
    "name": "asdf",
    "kind": "build"
  },
  "code": 404
}
```

Is this acceptable or should it be improved?

**Comment by TomasTomecek** [comment]
Fine with me.

**Comment by mmilata** [comment]
I'll close this then.
